### ISSUE TITLE
[Tracker] Tidy-up the codebase

### ISSUE THREAD

**Issue by debloper** [MozillaIndia/leaderboard#57]
- [ ] Move the components into separate directories
- [ ] Use GitModules, to keep the component reusable & un-coupled
- [ ] Cleanup JS, use closures and scope the methods under a namespace
- [ ] Use web-components ( ~~Mozilla Bricks?~~ ) for most of the templating works

**Comment by ngsankha** [comment]
Do we really need Mozilla Bricks? We don't even have a button on the leaderboard. If you ask me, just a plain CSS does good.

**Comment by debloper** [comment]
You are right... the overhead will be too much compared to the actual app.
We still can use native-templateing, though - better than pushing DOM-string with JS.
